/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ActionsButtons;
import Controllers.ActionsMenu;
import Models.HeaderTable;
import Models.HeaderTableViewModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import Models.LinesTableViewModel;
import Views.HeaderTableDialog;
import Views.LinesTablesDialog;

/**
 *
 * @author compu magic
 */
public class SalesInvoiceFrame extends javax.swing.JFrame 
{

    /**
     * Creates new form SalesInvoiceFrame
     */
    public SalesInvoiceFrame() {
                        initComponents();

         if(getInvoicesList().size()==0)
        {
         tblIteams.setVisible(false);
         btnSave.setVisible(false);
         btnCancel.setVisible(false);
        }
        

         

    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoices = new javax.swing.JTable();
        tblInvoices.getSelectionModel().addListSelectionListener(actionsButtons);
        btnCreatenewInvoice = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDelete.addActionListener(actionsButtons);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblInvoiceNumber = new javax.swing.JLabel();
        lblInvocieTotal = new javax.swing.JLabel();
        txtInvoiceCustomerName = new javax.swing.JTextField();
        txtInvocieDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIteams = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnSave.addActionListener(actionsButtons);
        btnCancel = new javax.swing.JButton();
        btnCancel.addActionListener(actionsButtons);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadFileMenu = new javax.swing.JMenuItem();
        SaveFileMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("SalesInvoices"); // NOI18N

        jLabel1.setText("Invoice Table");

        tblInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblInvoices);

        btnCreatenewInvoice.setText("Create New Invoice");
        btnCreatenewInvoice.setActionCommand("CreateNewInvoice");
        btnCreatenewInvoice.addActionListener(actionsButtons);

        btnDelete.setText("Delete Invoice");
        btnDelete.setActionCommand("DeleteInv");

        jLabel2.setText("Invoice Number");

        jLabel3.setText("Invoice Date");

        jLabel4.setText("Customer Name");
        jLabel4.setToolTipText("");

        jLabel5.setText("Invoice Total:");

        txtInvoiceCustomerName.setEditable(false);

        txtInvocieDate.setEditable(false);

        jLabel6.setText("Invoice Iteams");

        tblIteams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblIteams);

        btnSave.setText("Add New Line");
        btnSave.setActionCommand("SaveLine");

        btnCancel.setText("Remove Line");
        btnCancel.setActionCommand("CancelLine");

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        LoadFileMenu.setText("Load File");
        LoadFileMenu.setActionCommand("LoadFile");
        LoadFileMenu.addActionListener(actionsMenu);
        jMenu1.add(LoadFileMenu);

        SaveFileMenu.setText("Save File");
        SaveFileMenu.setActionCommand("SaveFile");
        SaveFileMenu.addActionListener(actionsMenu);
        jMenu1.add(SaveFileMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnCreatenewInvoice)
                                .addGap(70, 70, 70)
                                .addComponent(btnDelete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblInvoiceNumber)
                                            .addComponent(lblInvocieTotal)
                                            .addComponent(txtInvocieDate, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(txtInvoiceCustomerName)))
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addGap(116, 116, 116)
                                        .addComponent(btnCancel)
                                        .addGap(117, 117, 117)))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblInvoiceNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtInvocieDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtInvoiceCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblInvocieTotal))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatenewInvoice)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(32, 32, 32))
        );

        btnSave.getAccessibleContext().setAccessibleName("AddNewLine");
        btnCancel.getAccessibleContext().setAccessibleName("RemoveLine");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesInvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesInvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesInvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesInvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesInvoiceFrame().setVisible(true);
            }
        });
    }
    
    private List<HeaderTable> InvHeaderTable=new ArrayList<>();
    private  HeaderTableViewModel headerTableViewModels;
    private  LinesTableViewModel linesTableViewModel;
    private ActionsMenu actionsMenu=new ActionsMenu(this);
    private ActionsButtons actionsButtons=new ActionsButtons(this);
   // private ArrayList<HeaderTable> invoicesArray;
    private HeaderTableDialog headerTableDialog;
    private LinesTablesDialog linesTablesDialog;
    public static SimpleDateFormat dateFormat=new SimpleDateFormat("dd-MM-yyyy");
    
    public LinesTableViewModel getLinesTableViewModel() {
        return linesTableViewModel;
    }

    public void setLinesTableViewModel(LinesTableViewModel linesTableViewModel) {
        this.linesTableViewModel = linesTableViewModel;
    }

   

    
    public List<HeaderTable> getInvoicesList() 
    {
       
        return InvHeaderTable;
    }
    

    public LinesTablesDialog getLinesTablesDialog() {
        return linesTablesDialog;
    }

    public void setLinesTablesDialog(LinesTablesDialog linesTablesDialog) {
        this.linesTablesDialog = linesTablesDialog;
    }
    
   
    
    public ActionsButtons getListener() 
    {
        return actionsButtons;
    }

    public SalesInvoiceFrame(HeaderTableDialog headerTableDialog) {
        this.headerTableDialog = headerTableDialog;
    }
    
    public  void SalesInvoiceFrame(LinesTablesDialog linesTablesDialog)
    {
        this.linesTablesDialog=linesTablesDialog;
    }
    
    
    public HeaderTableViewModel getHeaderTableViewModels() {
        return headerTableViewModels;
    }
    public void setHeaderTableViewModels(HeaderTableViewModel headerTableViewModels) {
        this.headerTableViewModels = headerTableViewModels;
    }
    /*
    public SalesInvoiceFrame(HeaderTableViewModel headerTableViewModels) {
        this.headerTableViewModels = headerTableViewModels;
    }*/

    
    
    public void setInvoicesArray(ArrayList<HeaderTable> invoicesArray)
    {
        this.InvHeaderTable = invoicesArray;
    }
    
    

    public JTable getTblInvoices() 
    {
        return tblInvoices;
    }

   
    

    public JTable getTblIteams() {
        return tblIteams;
    }

   
    
    //Get Object of Header depend on headerNum
    public HeaderTable getHeaderObjectbyNum(int Code)
    {
        for(HeaderTable invtbl :InvHeaderTable)
        {
            if(invtbl.getInvoiceNumer()==Code)
                return invtbl;
        }
        return null;
    }

    public HeaderTableDialog getHeaderTableDialog() 
    {
        return headerTableDialog;
    }

    public void setHeaderTableDialog(HeaderTableDialog headerTableDialog) {
        this.headerTableDialog = headerTableDialog;
    }

    public JButton getBtnCreatenewInvoice() {
        return btnCreatenewInvoice;
    }
    
    public JLabel getLblInvocieTotal() {
        return lblInvocieTotal;
    }

    public JLabel getLblInvoiceNumber() {
        return lblInvoiceNumber;
    }

    public void setLblInvocieTotal(JLabel lblInvocieTotal) {
        this.lblInvocieTotal = lblInvocieTotal;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LoadFileMenu;
    private javax.swing.JMenuItem SaveFileMenu;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreatenewInvoice;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInvocieTotal;
    private javax.swing.JLabel lblInvoiceNumber;
    private javax.swing.JTable tblInvoices;
    private javax.swing.JTable tblIteams;
    private javax.swing.JTextField txtInvocieDate;
    private javax.swing.JTextField txtInvoiceCustomerName;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtInvocieDate() {
        return txtInvocieDate;
    }

    public JTextField getTxtInvoiceCustomerName() {
        return txtInvoiceCustomerName;
    }

    

    
}

